//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinManage.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinManage.Languages.Resources-RU", typeof(Resources_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить информацию.
        /// </summary>
        public static string AddInfoToFinManageButton {
            get {
                return ResourceManager.GetString("AddInfoToFinManageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение .
        /// </summary>
        public static string AmountAddFinManage {
            get {
                return ResourceManager.GetString("AmountAddFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        public static string AmountDataGridFinManage {
            get {
                return ResourceManager.GetString("AmountDataGridFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string CategoryAddInfoToFinManage {
            get {
                return ResourceManager.GetString("CategoryAddInfoToFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string CategoryDataGridFinManage {
            get {
                return ResourceManager.GetString("CategoryDataGridFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить информацию.
        /// </summary>
        public static string ChangeInfoFromFinManage {
            get {
                return ResourceManager.GetString("ChangeInfoFromFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта .
        /// </summary>
        public static string CurrencyAddInFinManage {
            get {
                return ResourceManager.GetString("CurrencyAddInFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта.
        /// </summary>
        public static string CurrencyDataGridFinManage {
            get {
                return ResourceManager.GetString("CurrencyDataGridFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата операции.
        /// </summary>
        public static string DateDataGridFinManage {
            get {
                return ResourceManager.GetString("DateDataGridFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата операции.
        /// </summary>
        public static string DateOperationAddInFinManage {
            get {
                return ResourceManager.GetString("DateOperationAddInFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить информацию.
        /// </summary>
        public static string DeleteInfoFromFinManage {
            get {
                return ResourceManager.GetString("DeleteInfoFromFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string DescriptionAddFinManage {
            get {
                return ResourceManager.GetString("DescriptionAddFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание .
        /// </summary>
        public static string DescriptionDataGridFinManage {
            get {
                return ResourceManager.GetString("DescriptionDataGridFinManage", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Ищет локализованную строку, похожую на Финансовая таблица.
        /// </summary>
        public static string FinTableFinManage {
            get {
                return ResourceManager.GetString("FinTableFinManage", resourceCulture);
            }
        }
        
        /// <summary>
=======
>>>>>>> fb0e37827c3d831f15c1b53518f83e303e0d1959
        ///   Ищет локализованную строку, похожую на Название места.
        /// </summary>
        public static string NameOfAmountDataGridFinManage {
            get {
                return ResourceManager.GetString("NameOfAmountDataGridFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название места.
        /// </summary>
        public static string NameOfStoreAddFinManage {
            get {
                return ResourceManager.GetString("NameOfStoreAddFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип операции.
        /// </summary>
        public static string OperationTypeDataGridFinManage {
            get {
                return ResourceManager.GetString("OperationTypeDataGridFinManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип операции.
        /// </summary>
        public static string TypeOperationInfoFinManage {
            get {
                return ResourceManager.GetString("TypeOperationInfoFinManage", resourceCulture);
            }
        }
    }
}
